<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.31.0" />
    <PackageReference Include="SkiaSharp" Version="4.151.4" />
    <PackageReference Include="TesseractOCR" Version="5.5.2" />
  </ItemGroup>

</Project>
